# create database SalesProfitDB;

select * from sales_data;

-- Find the total number of records in the dataset.

SELECT COUNT(*) AS TotalRecords FROM sales_data;

-- List all unique product categories.

SELECT DISTINCT Category FROM sales_data;


-- Find the earliest and latest sales dates.

SELECT MIN(Date) AS EarliestDate, MAX(Date) AS LatestDate FROM sales_data;


-- What is the total number of units sold?

SELECT SUM(UnitsSold) AS TotalUnits FROM sales_data;

-- What is the average price of products sold?

SELECT AVG(Price) AS AvgPrice FROM sales_data;


-- Which region has the highest total sales?


SELECT Region, SUM(NetSales) AS TotalSales 
FROM sales_data 
GROUP BY Region 
ORDER BY TotalSales DESC 
LIMIT 1;


--  How many units were sold in each region?

SELECT Region, SUM(UnitsSold) AS TotalUnits 
FROM sales_data 
GROUP BY Region;


-- Category Analysis

-- What is the total profit generated by each category ? 

SELECT Category, SUM(Profit) AS TotalProfit 
FROM sales_data 
GROUP BY Category 
ORDER BY TotalProfit DESC;

-- Which category has the highest average discount?


SELECT Category, AVG(Discount) AS AvgDiscount 
FROM sales_data 
GROUP BY Category 
ORDER BY AvgDiscount DESC 
LIMIT 1;


-- Time-Based Analysis

-- What are the monthly total sales? 

SELECT DATE_FORMAT(Date, '%Y-%m') AS Month, SUM(NetSales) AS MonthlySales 
FROM sales_data 
GROUP BY Month 
ORDER BY Month;

-- Which month had the lowest profit?

SELECT DATE_FORMAT(Date, '%Y-%m') AS Month, SUM(Profit) AS MonthlyProfit 
FROM sales_data 
GROUP BY Month 
ORDER BY MonthlyProfit ASC 
LIMIT 1;


--  What is the total discount given?

SELECT SUM(DiscountAmount) AS TotalDiscount FROM sales_data;

-- How do discounts correlate with profit?

SELECT Discount, AVG(Profit) AS AvgProfit 
FROM sales_data 
GROUP BY Discount 
ORDER BY Discount;

-- Product Insights

-- Which product generated the highest profit?

SELECT ProductName, SUM(Profit) AS TotalProfit 
FROM sales_data 
GROUP BY ProductName 
ORDER BY TotalProfit DESC 
LIMIT 1;

-- Which product category has the highest gross sales?

SELECT Category, SUM(GrossSales) AS TotalGrossSales 
FROM sales_data 
GROUP BY Category 
ORDER BY TotalGrossSales DESC;


-- Advanced Insights

-- Which region contributed to 80% of total sales?


SELECT Region, SUM(NetSales) AS TotalSales, 
       SUM(SUM(NetSales)) OVER (ORDER BY SUM(NetSales) DESC) / SUM(NetSales) OVER () AS CumulativePercentage 
FROM sales_data 
GROUP BY Region 
HAVING CumulativePercentage <= 0.8;


-- What is the most profitable region for each category?

SELECT Category, Region, SUM(Profit) AS TotalProfit 
FROM sales_data 
GROUP BY Category, Region 
ORDER BY Category, TotalProfit DESC;


-- Category and Region Analysis

-- Which category has the highest total sales in North America?

SELECT Category, SUM(NetSales) AS TotalSales 
FROM sales_data 
WHERE Region = 'North America' 
GROUP BY Category 
ORDER BY TotalSales DESC 
LIMIT 1;

-- What percentage of total sales does each region contribute?

SELECT Region, 
       SUM(NetSales) AS TotalSales, 
       (SUM(NetSales) / (SELECT SUM(NetSales) FROM sales_data) * 100) AS Percentage 
FROM sales_data 
GROUP BY Region;

-- Profitability Analysis

-- What is the profit margin for each product category?

SELECT Category, 
       SUM(Profit) / SUM(NetSales) * 100 AS ProfitMargin 
FROM sales_data 
GROUP BY Category;

-- What is the total loss (if any) across all transactions?

SELECT SUM(Profit) AS TotalLoss 
FROM sales_data 
WHERE Profit < 0;

-- Sales Trends and Patterns

-- Which quarter generates the highest revenue?

SELECT QUARTER(Date) AS Quarter, SUM(NetSales) AS TotalRevenue 
FROM sales_data 
GROUP BY Quarter 
ORDER BY TotalRevenue DESC 
LIMIT 1;

-- How has the discount percentage trended over the years?

SELECT YEAR(Date) AS Year, AVG(Discount) AS AvgDiscount 
FROM sales_data 
GROUP BY Year 
ORDER BY Year;

-- Customer and Behavioral Insights

-- Which category has the highest repeat purchases?

SELECT Category, COUNT(*) AS RepeatPurchases 
FROM sales_data 
WHERE CustomerID IN (SELECT CustomerID 
                     FROM sales_data 
                     GROUP BY CustomerID 
                     HAVING COUNT(*) > 1) 
GROUP BY Category 
ORDER BY RepeatPurchases DESC;


-- What is the average sales amount per transaction for each category?

SELECT Category, AVG(NetSales) AS AvgSalesPerTransaction 
FROM sales_data 
GROUP BY Category;


-- Advanced Analytics

-- Identify the top 3 products contributing to 50% of total sales.

SELECT ProductName, SUM(NetSales) AS TotalSales, 
       SUM(SUM(NetSales)) OVER (ORDER BY SUM(NetSales) DESC) / SUM(NetSales) OVER () AS CumulativePercentage 
FROM sales_data 
GROUP BY ProductName 
HAVING CumulativePercentage <= 0.5 
ORDER BY TotalSales DESC 
LIMIT 3;

-- What are the top 3 most profitable regions for the Electronics category?

SELECT Region, SUM(Profit) AS TotalProfit 
FROM sales_data 
WHERE Category = 'Electronics' 
GROUP BY Region 
ORDER BY TotalProfit DESC 
LIMIT 3;


-- Insights

-- How does average profit vary by discount ranges?

SELECT CASE 
         WHEN Discount BETWEEN 0 AND 5 THEN '0-5%' 
         WHEN Discount BETWEEN 6 AND 10 THEN '6-10%' 
         WHEN Discount BETWEEN 11 AND 15 THEN '11-15%' 
         ELSE '15%+' 
       END AS DiscountRange, 
       AVG(Profit) AS AvgProfit 
FROM sales_data 
GROUP BY DiscountRange;

-- What is the average sales-to-profit ratio for each category?

SELECT Category, AVG(NetSales / Profit) AS SalesToProfitRatio 
FROM sales_data 
GROUP BY Category;

-- Identify products with above-average sales and below-average profit.

SELECT ProductName, NetSales, Profit 
FROM sales_data 
WHERE NetSales > (SELECT AVG(NetSales) FROM sales_data) 
  AND Profit < (SELECT AVG(Profit) FROM sales_data);
















